name: Configure `~/.m2/toolchains.xml`
on:
  push:
permissions:
  contents: read
jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Show original `~/.m2/toolchains.xml`.
        run: cat ~/.m2/toolchains.xml || echo "File is absent"
      - name: Set up JDKs
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          java-version: |
            24-ea
            17
          distribution: temurin
      - name: Show `~/.m2/toolchains.xml` after `actions/setup-java`.
        run: cat ~/.m2/toolchains.xml
