name: Configure `~/.m2/toolchains.xml`
on:
  push:
permissions:
  contents: read
jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Show original `~/.m2/toolchains.xml`.
        run: cat ~/.m2/toolchains.xml || echo "File is absent"
      - name: Set up JDKs
        uses: s4u/setup-maven-action@4f7fb9d9675e899ca81c6161dadbba0189a4ebb1 # v1.18.0
        with:
          java-version: |
            24-ea
            17
          java-distribution: temurin
      - name: Show `~/.m2/toolchains.xml` after `s4u/setup-maven-action`.
        run: cat ~/.m2/toolchains.xml
